version: "3.5"

networks:
  app-network:
    driver: bridge

services:

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./php-fpm/php8.2.ini:/usr/local/etc/php/php.ini
      - ${APP_FILES_PATH}:/var/www
    restart: always
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - /var/log/nginx
      - ${APP_FILES_PATH}:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
    networks:
      - app-network

volumes:
  db_data:
  db_logs:
